# -*- coding: utf-8 -*-
"""
/***************************************************************************
 classe
                                 A QGIS plugin
 susceptibility
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-01
        copyright            : (C) 2021 by Giacomo Titti
        email                : giacomotitti@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Giacomo Titti, Cristobal A. Padilla Moreno'
__email__ = "cristobalpadilla@gmail.com"
__date__ = '2021-07-01'
__copyright__ = '(C) 2021 by Giacomo Titti, (C) 2026 by Cristobal A. Padilla Moreno'

# Acknowledgements:
# - UI layout initially designed with Qt Designer.
# - Code logic and algorithms partially authored with the assistance of AI (Gemini, Claude).

import os
from qgis.gui import QgsMessageBar
from qgis.core import Qgis
import sys

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load classe class from file classe.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .szr_module import classePlugin
    return classePlugin()

