# -*- coding: utf-8 -*-

"""
/***************************************************************************
 classe
                                 A QGIS plugin
 susceptibility
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-01
        copyright            : (C) 2021 by Giacomo Titti
        email                : giacomotitti@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Giacomo Titti, Cristobal A. Padilla Moreno'
__email__ = "cristobalpadilla@gmail.com"
__date__ = '2021-07-01'
__copyright__ = '(C) 2021 by Giacomo Titti, (C) 2026 by Cristobal A. Padilla Moreno'

# Acknowledgements:
# - UI layout initially designed with Qt Designer.
# - Code logic and algorithms partially authored with the assistance of AI (Gemini, Claude).

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect
from qgis.core import QgsApplication
from qgis.PyQt.QtCore import QSettings, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.utils import iface
from .installer.installer import installer
from .utils import log, warn

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class classePlugin(object):

    def __init__(self):
        self.provider = None
        self.dialog = None
        dir=(os.path.dirname(os.path.abspath(__file__)))
        with open(dir+'/metadata.txt','r') as file:
            for line in file:
                if line.startswith('version='):
                    self.version = line.strip().split('version=')[1].strip()
        self.plugin_settings = QSettings("SZR", str(self.version))

    def initProcessing(self):
        from .szr_module_provider import classeProvider
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = classeProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.installer = installer(self.version)

        if not self._ensure_dependencies():
            self.installer.unload()
            log("An error occured during the installation")
            raise RuntimeError("An error occured during the installation")

        self.plugin_settings.setValue("installed", True)
        self.initProcessing()

        # ── GUI entry point ──────────────────────────────────────────────────
        self.edu_action = QAction(
            QIcon(os.path.join(cmd_folder, 'icon.svg')),
            'SZR+ (Susceptibility Zoning + Raster capabilities)',
            iface.mainWindow()
        )
        self.edu_action.triggered.connect(self._open_panel)
        iface.addPluginToMenu('SZR+', self.edu_action)
        iface.addToolBarIcon(self.edu_action)

    def _ensure_dependencies(self):
        """Make the plugin's virtual-environment importable, provisioning it if needed.

        Once an environment has been provisioned it is activated in-process,
        which costs no subprocess call. The slow path (creating the venv, running
        ensurepip and querying pip for every requirement) therefore only runs on
        the first start, or when a dependency has gone missing.
        """
        if (self.plugin_settings.value("installed", False, type=bool)
                and self.installer.activate_env()):
            return True

        if self.installer.preliminay_req() is False:
            return False
        if self.installer.requirements() is False:
            return False
        return True

    DEFAULT_PANEL_SIZE = (1150, 720)

    def _open_panel(self):
        """Show the SZR+ window, creating it on first use."""
        if self.dialog is None:
            # Imported here so Qt widgets are only built once QGIS is ready.
            from qgis.PyQt.QtWidgets import QDialog, QVBoxLayout
            from .New_GUI.sz_edu_dialog import SzEduPanel

            # A child dialog of the main window is what earns the native frame
            # and the QGIS icon beside the title. A dock widget can show
            # neither: while floating it is a Qt::Tool window, and Windows
            # draws no caption icon on a tool window however the icon is set.
            self.dialog = QDialog(iface.mainWindow())
            self.dialog.setObjectName('SZRPlusPanel')
            self.dialog.setWindowTitle(
                'SZR+ (Susceptibility Zoning + Raster capabilities)')
            # Plain dialogs get only a close button; the panel is large enough
            # to be worth minimising and maximising.
            self.dialog.setWindowFlags(
                Qt.Dialog | Qt.WindowSystemMenuHint
                | Qt.WindowMinimizeButtonHint | Qt.WindowMaximizeButtonHint
                | Qt.WindowCloseButtonHint)

            layout = QVBoxLayout(self.dialog)
            layout.setContentsMargins(0, 0, 0, 0)
            layout.addWidget(SzEduPanel(self.dialog))

            self.dialog.finished.connect(self._save_panel_state)
            self._restore_panel_state()

        self.dialog.show()
        self.dialog.raise_()
        self.dialog.activateWindow()
        # Re-check after showing: the window manager can reposition a window as
        # it is mapped, and the monitor layout may have changed since the
        # position was saved.
        self._move_onto_screen()

    def _screen_for_main_window(self):
        """The screen QGIS is currently on (not necessarily the primary one)."""
        from qgis.PyQt.QtWidgets import QApplication
        main = iface.mainWindow()
        if main is not None:
            handle = main.windowHandle()
            if handle is not None and handle.screen() is not None:
                return handle.screen()
            screen = QApplication.screenAt(main.frameGeometry().center())
            if screen is not None:
                return screen
        return QApplication.primaryScreen()

    def _move_onto_screen(self):
        """Keep the window fully inside a visible screen.

        The window carries its own placement, so without this it can open beyond
        the edge of a secondary monitor (or on a monitor that is no longer
        attached).

        Note resize() sets the *inner* size while move() positions the *frame*,
        so the window-manager decorations have to be budgeted separately —
        feeding frame dimensions into resize() makes the window grow each call.
        """
        if self.dialog is None or self.dialog.isMaximized():
            return

        avail = self._screen_for_main_window().availableGeometry()
        frame = self.dialog.frameGeometry()
        inner = self.dialog.geometry()
        dw = max(0, frame.width() - inner.width())
        dh = max(0, frame.height() - inner.height())

        new_w = min(inner.width(), max(200, avail.width() - dw))
        new_h = min(inner.height(), max(200, avail.height() - dh))
        if (new_w, new_h) != (inner.width(), inner.height()):
            self.dialog.resize(new_w, new_h)

        frame = self.dialog.frameGeometry()    # re-read after any resize
        x = min(max(frame.x(), avail.x()), avail.x() + avail.width() - frame.width())
        y = min(max(frame.y(), avail.y()), avail.y() + avail.height() - frame.height())
        if (x, y) != (frame.x(), frame.y()):
            self.dialog.move(x, y)

    def _centre_panel(self):
        """Centre the window on the QGIS main window."""
        main = iface.mainWindow()
        avail = self._screen_for_main_window().availableGeometry()

        self.dialog.resize(min(self.DEFAULT_PANEL_SIZE[0], avail.width() - 120),
                           min(self.DEFAULT_PANEL_SIZE[1], avail.height() - 120))

        frame = self.dialog.frameGeometry()
        ref = main.frameGeometry() if main is not None else avail
        self.dialog.move(ref.x() + (ref.width() - frame.width()) // 2,
                         ref.y() + (ref.height() - frame.height()) // 2)
        self._move_onto_screen()

    def _restore_panel_state(self):
        """Reopen the window where the user last left it, when that is still valid."""
        from qgis.PyQt.QtCore import QRect
        from qgis.PyQt.QtWidgets import QApplication

        geom = self.plugin_settings.value("panel/geometry")

        rect = None
        try:
            if geom:
                x, y, w, h = (int(v) for v in geom)
                if w > 200 and h > 200:
                    rect = QRect(x, y, w, h)
        except (TypeError, ValueError):
            rect = None

        # Only reuse a saved position if a screen still covers it — otherwise the
        # window would reopen on a monitor that is no longer there.
        if rect is not None and any(s.availableGeometry().intersects(rect)
                                    for s in QApplication.screens()):
            # rect holds the frame position and the inner size (see _save_panel_state)
            self.dialog.resize(rect.width(), rect.height())
            self.dialog.move(rect.x(), rect.y())
            self._move_onto_screen()
        else:
            self._centre_panel()

    def _save_panel_state(self):
        """Remember the window's placement for the next session."""
        if self.dialog is None:
            return
        try:
            if self.dialog.isMaximized() or self.dialog.isMinimized():
                return          # keep the last ordinary placement instead
            # Frame position (what move() takes) with the inner size (what
            # resize() takes), so the pair round-trips through restore.
            pos = self.dialog.frameGeometry()
            size = self.dialog.geometry()
            self.plugin_settings.setValue(
                "panel/geometry",
                [pos.x(), pos.y(), size.width(), size.height()])
        except RuntimeError:
            pass                        # dialog already destroyed on the C++ side

    def unload(self):
        if self.provider is not None:
            QgsApplication.processingRegistry().removeProvider(self.provider)
            self.provider = None
        if hasattr(self, 'edu_action'):
            iface.removePluginMenu('SZR+', self.edu_action)
            iface.removeToolBarIcon(self.edu_action)
        if self.dialog is not None:
            self._save_panel_state()
            self.dialog.close()
            self.dialog.deleteLater()   # also deletes the panel it owns
            self.dialog = None
