# -*- coding: utf-8 -*-

"""
/***************************************************************************
 classe
                                 A QGIS plugin
 susceptibility
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-01
        copyright            : (C) 2021 by Giacomo Titti
        email                : giacomotitti@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Giacomo Titti, Cristobal A. Padilla Moreno'
__email__ = "cristobalpadilla@gmail.com"
__date__ = '2021-07-01'
__copyright__ = '(C) 2021 by Giacomo Titti, (C) 2026 by Cristobal A. Padilla Moreno'

# Acknowledgements:
# - UI layout initially designed with Qt Designer.
# - Code logic and algorithms partially authored with the assistance of AI (Gemini, Claude).

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect
from qgis.core import QgsApplication
from qgis.PyQt.QtCore import QSettings
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.utils import iface, available_plugins, active_plugins
from .installer.installer import installer
from .utils import log, warn

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class classePlugin(object):

    def __init__(self):
        #self.settings = QgsSettings()
        #self.settings.beginGroup("SZ")

        self.provider = None
        dir=(os.path.dirname(os.path.abspath(__file__)))
        with open(dir+'/metadata.txt','r') as file:
            for line in file:
                if line.startswith('version='):
                    self.version = line.strip().split('version=')[1].strip()
        self.plugin_settings = QSettings("SZR", str(self.version))

    def initProcessing(self):
        from .szr_module_provider import classeProvider
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = classeProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.installer=installer(self.version)
        print('Plugin already installed? ',self.plugin_settings.value("installed"))
        #if not self.plugin_settings.value("installed"):# or self.plugin_settings.value("active"):
        print('0')
        if self.installer.preliminay_req() is False:
            self.installer.unload()
            log(f"An error occured during the installation")
            raise RuntimeError("An error occured during the installation")
        else:
            print('1')
            if self.installer.requirements() is False:
                self.installer.unload()
                log(f"An error occured during the installation")
                raise RuntimeError("An error occured during the installation")
            else:
                print('2')
                self.plugin_settings.setValue("installed", True)
                self.initProcessing()
                # ── Educational GUI entry point ──────────────────────────────
                self.edu_action = QAction(
                    QIcon(os.path.join(cmd_folder, 'icon.svg')),
                    'SZR+ (Susceptibility Zoning + Raster capabilities)',
                    iface.mainWindow()
                )
                self.edu_action.triggered.connect(self._open_edu_dialog)
                iface.addPluginToMenu('SZR+', self.edu_action)
                iface.addToolBarIcon(self.edu_action)
        # if self.plugin_settings.value("installed"):
        #     print('3')
        #     self.initProcessing()

    def _open_edu_dialog(self):
        """Open the standalone SZR+ dialog."""
        # Import here to avoid loading Qt widgets before QGIS is ready
        from .New_GUI.sz_edu_dialog import SzEduDialog
        
        # Persist the instance so it floats and stays open
        if getattr(self, 'edu_dlg', None) is None:
            self.edu_dlg = SzEduDialog(iface.mainWindow())
        self.edu_dlg.show()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
        if hasattr(self, 'edu_action'):
            iface.removePluginMenu('SZR+', self.edu_action)
            iface.removeToolBarIcon(self.edu_action)
        #self.installer.unload()




            
          